version: 0.0.1
host: 127.0.0.1
port: 8071
bot:
  auto:
    adb:
      device_name: "127.0.0.1:16384"
      delay: 0.5
    cpu_alloc: 4

test:
  log_level: "DEBUG"
  web_log_level: "INFO"
  log_path: "./log"
  log_name: "log.log"
  save_screen: false
  save_screen_path: "./log/screen"


bluestacks:
  path: C:\Program Files\BlueStacks_nxt_cn\HD-Player.exe
  check_config: True
  close_bluestacks: True
  bluestacks_conf: E:\BlueStacks_nxt_cn\BlueStacks_nxt_cn\bluestacks.conf
  instance: bst.instance.Pie64
  fb_height: 1280
  fb_width: 720
  gl_win_screen: \\.\DISPLAY2
  dpi: 180

event:
  path: "./event.json"
  use_wiki: True
  wiki_path: "https://wiki.biligame.com/umamusume/"
